set_property PACKAGE_PIN Y1 [get_ports a]
set_property PACKAGE_PIN W3 [get_ports b]
set_property PACKAGE_PIN L4 [get_ports v]
set_property PACKAGE_PIN M4 [get_ports w]
set_property PACKAGE_PIN M2 [get_ports x]
set_property PACKAGE_PIN N7 [get_ports y]
set_property PACKAGE_PIN M7 [get_ports z]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports v]
set_property IOSTANDARD LVCMOS33 [get_ports w]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports z]

set_property BEL C6LUT [get_cells w_OBUF_inst_i_1]
set_property LOC SLICE_X85Y119 [get_cells w_OBUF_inst_i_1]
